INT_126_Arsh/force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

INT_125_Ritvik/force-app/main/default/objects/Bank_Account__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Loan Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

INT_125_Ritvik/force-app/main/default/objects/Bank_Account__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Bank Account</relationshipLabel>
    <relationshipName>Bank_Account</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

INT131_Sourav/force-app/main/default/objects/Bank_Account__c/fields/Customers__c.field-meta.xml
<CustomField>
    <fullName>Customers__c</fullName>
    <label>Customers</label>
    <referenceTo>Customers__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce_Assignment/force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

INT131_Sourav/force-app/main/default/objects/Customers__c/Customers__c.object-meta.xml
<CustomObject>
    <label>Customers</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

INT_127_Aayushi/force-app/main/default/classes/CustomerTriggerHandler.cls
public class CustomerTriggerHandler {
public void updateIsActive(list<Customer__c> customerList,Map<Id,Customer__c> oldmap){

        List<Id> custIds=new List<Id>();
        for(Customer__c cust:customerList){
            Customer__c oldcust=oldmap.get(cust.id);
            if(oldcust.Active__c!=cust.Active__c){
                system.debug('oldcust.Active__c '+oldcust.Active__c);
                system.debug('cust.Active__c '+cust.Active__c);
                if(cust.Active__c==false){
                custIds.add(cust.id);
                }
            }
        }
         List<Customer__c> custlsushd=new List<Customer__c>();
        Boolean  isLoan=false;
         system.debug('custIds '+custIds);
        for(Customer__c cus: [select Name,Active__c,(select Name,RecordtypeId,Recordtype.name,balance__c from Bank_accounts__r) from Customer__c where id IN : custIds])
        {  
            system.debug('cus '+cus);
            for(Bank_account__c bankAc:cus.Bank_accounts__r){
                 system.debug('bankAc '+bankAc);
                 system.debug('bankAc.Recordtype '+bankAc.Recordtype.name);
                if(bankAc.Recordtype.name=='Loan' && bankAc.balance__c==0){
                      system.debug('bankAc.Recordtype '+bankAc.Recordtype);
                    isLoan=true;
                   // bankAc.customers__r.Active__c=false;
                }  
            }
            if(isLoan){
               cus.Active__c=false;
                custlsushd.add(cus);
            }
            else{
                cus.Active__c=true;
                custlsushd.add(cus);
                Trigger.new[0].addError('You have a pending balance to mark yourself inactive make the balance 0');
                System.debug('error');
            }
        }
        update custlsushd;
         }
}