INT_126_Arsh/force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

INT131_Sourav/force-app/main/default/objects/Bank_Account__c/fields/Customers__c.field-meta.xml
<CustomField>
    <fullName>Customers__c</fullName>
    <label>Customers</label>
    <referenceTo>Customers__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

INT131_Sourav/force-app/main/default/objects/Bank_Account__c/fields/Loan_Balance__c.field-meta.xml
<CustomField>
    <fullName>Loan_Balance__c</fullName>
    <label>Loan Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

INT131_Sourav/force-app/main/default/objects/Customers__c/Customers__c.object-meta.xml
<CustomObject>
    <label>Customers</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

INT131_Sourav/force-app/main/default/classes/CustomersTriggerHandler.cls
public class CustomersTriggerHandler 
{
    public void updateIsActive(list<Customers__c> customList,Map<Id,Customers__c> oldmap)
    {
        List<Id> custIds=new List<Id>();
        for(Customers__c cust:customList)
        {
            Customers__c oldcust=oldmap.get(cust.id);
            if(oldcust.Active__c!=cust.Active__c)
            {
                system.debug('oldcust.Active__c '+oldcust.Active__c);
                system.debug('cust.Active__c '+cust.Active__c);
                if(cust.Active__c==false)
                {
                    custIds.add(cust.id);
                }
            }
        }
        List<Customers__c> custlsushd=new List<Customers__c>();
        Boolean  isLoan=false;
        system.debug('custIds '+custIds);
        for(Customers__c cus: [select Name,Active__c,(select Name,RecordtypeId,Recordtype.name,loan_balance__c from Bank_accounts__r) from Customers__c where id IN : custIds])
        {  
            system.debug('cus '+cus);
            for(Bank_account__c bankAc:cus.Bank_accounts__r)
            {
                system.debug('bankAc '+bankAc);
                system.debug('bankAc.Recordtype '+bankAc.Recordtype.name);
                if(bankAc.Recordtype.name=='Loan' && bankAc.loan_balance__c==0)
                {
                    system.debug('bankAc.Recordtype '+bankAc.Recordtype);
                    isLoan=true;
                }  
            }
            if(isLoan)
            {
                system.debug('inside siififf');
                cus.Active__c=false;
                custlsushd.add(cus);
            }
            else
            {
                cus.Active__c=true;
                custlsushd.add(cus);                
	            Trigger.new[0].addError('You have a pending loan Balance,To make yourself inactive your loan balance should be zero');
                System.debug('error');
            }
        }
        update custlsushd;
    }
}